### ISSUE TITLE
[Question] some questions about index freq 

### ISSUE THREAD

**Issue by rty813** [arkohut/pensieve#28]
1. I found that for the recorded screenshots, not every one is indexed, but only once every X number of times. So when the system is idle, will the previously skipped snapshots be re-indexed?
2. After the screen is locked, it does not seem to continue indexing in the background. I think that every night when the system is idle is a good time to re-index the previously unindexed pictures.

**Comment by arkohut** [comment]
Great question! 

Currently, Pensieve dynamically adjusts the processing intervals based on the screenshots processing speed. As a result, some screenshots are fully indexed, while others only have their file name, current application name, and title recorded. Additionally, if the system detects that it is running on battery power, the number of skipped screenshots will significantly increase.

Right now, the system does not automatically perform a full scan for unindexed content; Manually execute the command `memos scan` is required to trigger a full scan.

This topic is also mentioned here: https://github.com/arkohut/pensieve/issues/16.

**Comment by arkohut** [comment]
Currently, I will not automatically run the full scan because the computational power of each device varies. For instance, without an NVIDIA GPU, a full scan of one day’s data could take several hours or even longer.

However, Pensieve currently defaults to recording the screen every 4 seconds, adopting an approach of “recording more, processing less” to facilitate batch processing when sufficient computational power is available. If you think this approach is unnecessary, you can adjust the `record_interval` in the config file.

**Comment by rty813** [comment]
For example, my computer at work works for 8 hours during the day and is in standby mode for more than ten hours at night. This time can be fully utilized

**Comment by arkohut** [comment]
Ok, this may be a good feature. I will try to create a PR for it.
